kind: Service
apiVersion: v1
metadata:
  name: filewriter
  labels:
    app: filewriter
spec:
  type: NodePort
  selector:
    app: filewriter
  ports:
  - port: 8080
    targetPort: 8080
    name: http
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: filewriter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: filewriter
  template:
    metadata:
      labels:
        app: filewriter
        version: v1
    spec:
      containers:
      - name: filewriter
        image: filewriter
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
