kind: Service
apiVersion: v1
metadata:
  name: filereader
  labels:
    app: filereader
spec:
  type: NodePort
  selector:
    app: filereader
  ports:
  - port: 8080
    targetPort: 8080
    name: http
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: filereader
spec:
  replicas: 1
  selector:
    matchLabels:
      app: filereader
  template:
    metadata:
      labels:
        app: filereader
        version: v1
    spec:
      containers:
      - name: filereader
        image: filereader
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
